kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "Common": {
               "class": "Tenant",
               "Shared": {
                 "class": "Application",
                 "template": "shared",
                 "XFF_HTTP_Profile": {
                 "class": "HTTP_Profile",
                 "xForwardedFor": true
                 }
               }
            },
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.7"
                        ],
                        "virtualPort": 80,
                        "remark":"ingress: f5demo.waf.http.v1",
                        "pool": "web_pool",
                        "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
                        "policyWAF":{"use": "My_ASM_Policy"},
                        "securityLogProfiles": [
                        {
                            "bigip": "/Common/Log all requests"
                        }
                        ]
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "My_ASM_Policy": {
                      "class": "WAF_Policy",
                      "url": "https://gitlab.foobz.com.au/fbchan/awaf-policies/raw/master/awaf-OWASP-Top10.xml",
                      "ignoreChanges": true
                    }
                }
            }
        }
    }
