kind: Service
apiVersion: v1
metadata:
  name: hackazone
  namespace: default
  labels:
    app: hackazone
    cis.f5.com/as3-tenant: AS3
    cis.f5.com/as3-app: A2
    cis.f5.com/as3-pool: hackazone_pool
spec:
  selector:
    app: hackazone
  ports:
  - name: hackazone
    protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazone-deploy
  namespace: default
  labels:
    app: hackazone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackazone
  template:
    metadata:
      labels:
        app: hackazone
    spec:
      containers:
      - name: hackazone
        image: mutzel/all-in-one-hackazon:postinstall
        ports:
        - containerPort: 80
