kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-declaration
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "Common": {
               "class": "Tenant",
               "Shared": {
                 "class": "Application",
                 "template": "shared",
                 "XFF_HTTP_Profile": {
                 "class": "HTTP_Profile",
                 "xForwardedFor": true
                 }
               }
            },
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.7"
                        ],
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "A2": {
                    "class": "Application",
                    "template": "generic",
                    "ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.8"
                        ],
                        "pool": "hackazone_pool"
                    },
                    "hackazone_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "A3": {
                    "class": "Application",
                    "template": "generic",
                    "ingress": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.6"
                        ],
                        "virtualPort": 80,
                        "remark":"ingress: nginx.waf.http.v1",
                        "pool": "nginx_pool",
                        "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
                        "policyWAF":{"bigip":"/Common/linux-low"},
                        "securityLogProfiles": [
                        {
                            "bigip": "/Common/Log all requests"
                        }
                        ]
                    },
                    "nginx_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
