kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-bt-demo
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "Common": {
               "class": "Tenant",
               "Shared": {
                 "class": "Application",
                 "template": "shared",
                 "XFF_HTTP_Profile": {
                 "class": "HTTP_Profile",
                 "xForwardedFor": true
                 }
               }
            },
            "BT_DEMO": {
                "class": "Tenant",
                "bt_demo_app": {
                    "class": "Application",
                    "template": "generic",
                    "bt_demo_ingress": {
                        "class": "Service_HTTPS",
                        "virtualAddresses": [
                            "10.2.1.6"
                        ],
                        "virtualPort": 443,
                        "remark":"ingress: better together demo app",
                        "pool": "bt_demo_pool",
                        "serverTLS": "bt_demo_webtls_local",
                        "profileHTTP":{"use": "/Common/Shared/XFF_HTTP_Profile"},
                        "policyWAF":{"bigip":"/Common/linux-low"},
                        "securityLogProfiles": [
                        {
                            "bigip": "/Common/Log illegal requests"
                        }
                        ]
                    },
                    "bt_demo_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    },
                    "bt_demo_webtls_local": {
                      "class": "TLS_Server",
                      "label": "simplest decl requires just cert",
                      "certificates": [
                        {
                          "certificate": "tlsserver_local_cert"
                        }
                      ]
                    },
                    "tlsserver_local_cert": {
                      "class": "Certificate",
                      "certificate": {"bigip":"/Common/default.crt"},
                      "privateKey": {"bigip":"/Common/default.key"}
                    }
                }
            }
        }
    }
