kind: Service
apiVersion: v1
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    cis.f5.com/as3-tenant: NGINX 
    cis.f5.com/as3-app: nginx_app
    cis.f5.com/as3-pool: nginx_pool
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
