kind: ConfigMap
apiVersion: v1
metadata:
  name: f5-as3-multi-apps
  namespace: default
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
        "class": "AS3",
        "declaration": {
            "class": "ADC",
            "schemaVersion": "3.10.0",
            "id": "urn:uuid:33045210-3ab8-4636-9b2a-c98d22ab915d",
            "label": "http",
            "remark": "Simple HTTP application with RR pool",
            "AS3": {
                "class": "Tenant",
                "A1": {
                    "class": "Application",
                    "template": "generic",
                    "f5_hello_world": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.7"
                        ],
                        "remark":"ingress: f5 hello world apps",
                        "pool": "web_pool"
                    },
                    "web_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 8080,
                                "serverAddresses": []
                            }
                        ]
                    }
                },
                "A2": {
                    "class": "Application",
                    "template": "generic",
                    "hackazone": {
                        "class": "Service_HTTP",
                        "virtualAddresses": [
                            "10.2.1.8"
                        ],
                        "remark":"ingress: hackazone non WAF",
                        "pool": "hackazone_pool"
                    },
                    "hackazone_pool": {
                        "class": "Pool",
                        "monitors": [
                            "http"
                        ],
                        "members": [
                            {
                                "servicePort": 80,
                                "serverAddresses": []
                            }
                        ]
                    }
                }
            }
        }
    }
